### MONITORS ###
monitor = eDP-1, preferred, 0x0, 1.666667
monitor = , preferred, 0x0, 1

### WORKSPACES ###
workspace = 1, persistent:true, default:true, defaultName:Algorithms
workspace = 2, persistent:true, defaultName:Paradigms
workspace = 3, persistent:true, defaultName:Web
workspace = 4, persistent:true, defaultName:Div

### PROGRAMS ###
$terminal = alacritty
$fileManager = nemo
$menu = rofi -show drun
$browser = brave

### AUTOSTART ###
exec-once = waybar &
exec-once = hypridle &
exec-once = swww-daemon
exec-once = sleep 3 && ~/.config/scripts/wallpaper_rotate.sh &
exec-once = nm-applet --indicator &
exec-once = hyprpolkitagent &
exec-once = wl-clip-persist --clipboard regular &
exec-once = ~/.config/scripts/notifications/notify_bluetooth.sh &
exec-once = nextcloud --background
exec-once = ~/.config/scripts/notifications/hypr-osd/target/release/hypr-osd

### SOURCES ###
source = ~/.config/hypr/hypr_custom/window_rules.conf
source = ~/.config/hypr/hypr_custom/look_feel.conf
source = ~/.config/hypr/hypr_custom/keybinds.conf














