

# Commands that should be applied only for interactive shells.
[[ $- == *i* ]] || return

HISTFILESIZE=100000
HISTSIZE=10000

shopt -s histappend
shopt -s extglob
shopt -s globstar
shopt -s checkjobs

alias config='cd "$HOME/.config"'
alias dl='cd "$HOME/Downloads"'
alias doc='cd "$HOME/Documents"'
alias doodle='cd "$HOME/edu/doodle"'
alias edu='cd "$HOME/edu"'
alias home='cd "$HOME"'
alias nixconfig='cd "/etc/nixos"'

if [[ ! -v BASH_COMPLETION_VERSINFO ]]; then
  . "/nix/store/czv02wicy8w7y11sx18zq9lnqxsbj3pc-bash-completion-2.17.0/etc/profile.d/bash_completion.sh"
fi

