### ENVIRONMENT VARIABLES ###

# See https://wiki.hyprland.org/Configuring/Environment-variables/
#windowrulev2 = float, class:(zoom)
#windowrulev2 = center,class:(zoom)
#windowrulev2 = size 50% 50%, class:(zoom)
# PulseAudio Control - Laptop Display (eDP-1: 1600x1000)
windowrulev2 = float,class:(org.pulseaudio.pavucontrol)
windowrulev2 = size 900 700, class:(org.pulseaudio.pavucontrol)
windowrulev2 = center, class:(org.pulseaudio.pavucontrol)

windowrulev2 = nofocus, class:^(zoom)$, title:^(menu window)$

# NetworkManager Connection Editor - Laptop Display
windowrulev2 = float, class:(nm-connection-editor)
windowrulev2 = size 900 700, class:(nm-connection-editor)
windowrulev2 = center, class:(nm-connection-editor) 
# NetworkManager Connection Editor - External 1440p
#windowrulev2 = float, title:(File Upload)
#windowrulev2 = center, title:(File Upload)
#windowrulev2 = size 50% 50%, title:(File Upload)



# Ignore maximize requests from apps. You'll probably like this.
windowrulev2 = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more


